# This is a basic workflow to help you get started with Actions

name: nix CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hb:
    runs-on: ubuntu-latest

    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: nix-build --argstr job "_deps"
    - name: Build HB
      run: nix-build --argstr job "hierarchy-builder"

  hb-shim:
    runs-on: ubuntu-latest

    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: nix-build --argstr job "_deps"
    - name: Build HB shim
      run: nix-build --argstr job "hierarchy-builder-shim"

  mathcomp:
    runs-on: ubuntu-latest
    needs: hb
    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: nix-build --argstr job "_deps"
    - name: Hiearchy builder
      run: nix-build --argstr job "hierarchy-builder"
    - name: Build mathcomp on HB
      run: nix-build --argstr job "mathcomp-single"

  mathcomp-planB-src:
    runs-on: ubuntu-latest
    needs: hb
    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: nix-build --argstr job "_deps"
    - name: Hiearchy builder
      run: nix-build --argstr job "hierarchy-builder"
    - name: Build planB sources
      run: nix-build --argstr job "mathcomp-single-planB-src"

  mathcomp-planB:
    runs-on: ubuntu-latest
    needs:
    - hb-shim
    - mathcomp-planB-src
    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dependencies
      run: nix-build --argstr job "_deps"
    - name: Hiearchy builder
      run: nix-build --argstr job "hierarchy-builder-shim"
    - name: Build plan B sources
      run: nix-build --argstr job "mathcomp-single-planB-src"
    - name: Build plan B
      run: nix-build --argstr job "mathcomp-single-planB"
