# This is a basic workflow to help you get started with Actions

name: nix CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hb:
    runs-on: ubuntu-latest

    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: nix-build

  mathcomp:
    runs-on: ubuntu-latest
    needs: hb
    steps:
    - name: Cachix install
      uses: cachix/install-nix-action@v12
    - name: Cachix setup
      uses: cachix/cachix-action@v8
      with:
        name: math-comp
        extraPullNames: coq
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: nix-build --arg ci true
